name: prototypes

dependencies:
  - base >= 4.7 && < 5

ghc-options: -Wall

executables:
  Action:
    main: Action.hs
    dependencies:
      - transformers
  Async:
    main: Async.hs
  ConfigLang:
    main: ConfigLang.hs
    dependencies:
      - containers
      - megaparsec
      - mtl
      - parser-combinators
      - text
  Cont:
    main: Cont.hs
    dependencies:
      - containers
  ContChain:
    main: ContChain.hs
    dependencies:
      - transformers
  ContraTuple:
    main: ContraTuple.hs
    dependencies:
      - transformers
  ContResource:
    main: ContResource.hs
    dependencies:
      - transformers
  Curry:
    main: Curry.hs
  FunctionRecord:
    main: FunctionRecord.hs
    dependencies:
      - containers
      - megaparsec
      - mtl
      - parser-combinators
      - text
      - transformers
  Futamura:
    main: Futamura.hs
  Generator:
    main: Generator.hs
  Invertible:
    main: Invertible.hs
  Lambda:
    main: Lambda.hs
    dependencies:
      - mtl
  Lens:
    main: Lens.hs
  MacroInterp:
    main: MacroInterp.hs
    dependencies:
      - megaparsec
      - parser-combinators
  Memoize:
    main: Memoize.hs
    dependencies:
      - containers
      - transformers
  Multiplicity:
    main: Multiplicity.hs
    dependencies:
      - mtl
  Optics:
    main: Optics.hs
  Pattern:
    main: Pattern.hs
  PatternLift:
    main: PatternLift.hs
  Pipe:
    main: Pipe.hs
  PolyCons:
    main: PolyCons.hs
  Printf:
    main: Printf.hs
  RecurseWithoutSelfRef:
    main: RecurseWithoutSelfRef.hs
  Res:
    main: Res.hs
  Rope:
    main: Rope.hs
  Step:
    main: Step.hs
  Template:
    main: Template.hs
    dependencies:
      - megaparsec
      - parser-combinators
      - mtl
      - containers
