name: prototypes

dependencies:
  - base >= 4.7 && < 5

ghc-options: -Wall

executables:
  MacroInterp:
    main: MacroInterp.hs
    dependencies:
      - megaparsec
      - parser-combinators
  Generator:
    main: Generator.hs
  Action:
    main: Action.hs
    dependencies:
      - transformers
  Template:
    main: Template.hs
    dependencies:
      - megaparsec
      - parser-combinators
      - mtl
      - containers
  ConfigLang:
    main: ConfigLang.hs
    dependencies:
      - containers
      - megaparsec
      - mtl
      - parser-combinators
      - text
